### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/newyork_restaurant_grading#11]
_Congratulations on finishing milestone 1! Amazing work. 

You were able to address everything we wanted to touch on milestone 1. I look forward to seeing the progress of the project. I would only point out few things that you could improve in the EDA visualizations. 

**Exploratory data analysis in a literate code document**

- [x] The font size of the title for the figures can be increased.
- [x] The x-axis and the y-axis titles are, at times, too small compared to the size of the image. 
- [x] It is not a good choice to use titles like additional figures. You are telling a story using the data. Use captions that capture the reader's attention. I think there is good room for improvement in the storytelling side of your EDA.
