### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/newyork_restaurant_grading#29]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, Great work! 

 Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [x] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added -0.5 quality
**Comment:** Download_csv.py missing author, date etc. 
- [x] Table 2.3 text is very small and hard to read. Try and see if you can make the size of the text bigger. Same goes with text in Fig 3. Just a suggestion. 
- [ ] There are cases of functions that do not check for proper input data and/or do not provide useful error messages. -1 mechanics
- [x] Could not reproducibly run the analysis because a package was missing from the provided computational environment. -1 reasoning
**Comment:** Error while trying to build the environment. Problem was that ipykernel  is 16.8.0 . If you run conda search ipykernel you will see that this version is not available to download from Conda. Florencia corrected this by forking your repository- https://github.com/flor14/newyork_restaurant_grading/commit/bf523988cd2d2848e525eba69b3dca93ce578824. One of the requirements of this Milestone is that the code should be reproducible the first time I try to run it. 
- [ ] While running the scripts I get a lot of warning messages it is generally good practice to not have so many warnings generated try and see if you can correct this for the future milestones. Just a suggestion.
