### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/newyork_restaurant_grading#34]
**Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

# Automating the data-analysis pipeline using Make

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- [x] The `Makefile` is not well documented **- 2** **quality**
**Comments:** Missing documentation for all and clean

- [x] The Makefile does not have an clean (or similarly named) phony target that resets the entire analysis to the beginning state - 1 accuracy
**Comment:** make clean does not work because the spacing the wrong. Uses spaces rather than tab.

### Dependencies have been updated (so it include the test libraries)

Good job!

### Project file and directory structure organization
Good job!
###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-2** **mechanics**
**Comment:**  The "Clone the repository" section of usage, make sure to include the tag for the current milestone.

- [x] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5** **quality**
**Comment:** Could not install dependancies using conda based on envirnoment.yaml file.  There are dependancy conflicts, make sure you rerun the whole analysis from scratch including creating a new conda environment. 

### Follows GitHub flow version control workflow

Good job!
### GitHub release

- [x] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-2** **mechanics**
