### ISSUE TITLE
Milestone 4 - Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/newyork_restaurant_grading#55]
**Congratulations** on finishing milestone 4! Below we list some specific feedback you can use to improve your project.

**Dependency diagram of the Makefile (max 5 points)**
-----
Satisfactory.

**Make your project reproducible (to the max) with Docker**
-----
**Dockerfile**
- [ ]  The dependencie versions are not pinned. -2 quality
- [ ]  Programming language and/or package versions are pinned using >= instead of =. This means that each time the Docker image is built in the future, the most recent version of the programming language and/or package will be installed in the container image. This will lead to the container not being able to be reproducibly built in the future. -2 accuracy

**Analysis can be run reproducibly using documentation provided in the README**
Satisfactory.

**Final Submission: Improve the project based on the feedback received**
------
Satisfactory.

**Expectations**
------
- [ ] GitHub issues were not closed. -5 mechanics
